executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0.2'
orbs:
  maven: circleci/maven@1.3.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: java17